// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var config, fields;
    fields = ['repositories', 'title', 'labels', 'assignee', 'milestone', 'body'];
    config = {};
    chrome.storage.local.get(fields, function(items) {
      return fields.forEach(function(field) {
        return $('#' + field).val(items[field]);
      });
    });
    return $('#form').submit(function(e) {
      e.preventDefault();
      fields.forEach(function(field) {
        return config[field] = $.trim($('#' + field).val());
      });
      return chrome.storage.local.set(config, function() {
        return alert('Configurations are saved successfully.');
      });
    });
  });

}).call(this);
